"""GeoLibre & MapLibre Integration Engine for eo-mcp.

Bridges headless agentic planetary compute with interactive visual GIS:
1. Generates standalone, self-contained interactive MapLibre GL JS web maps with dark titanium styling.
2. Exports native GeoLibre-compatible project files (.geolibre / .json) for one-click import into GeoLibre.
3. Generates GeoAgent tool-call action sequences for live in-map agent choreography.

References:
- GeoLibre Platform: https://github.com/opengeos/GeoLibre
- MapLibre GL JS: https://maplibre.org/maplibre-gl-js/docs/
- maplibre-gl-geoagent: https://github.com/opengeos/maplibre-gl-geoagent
"""

import json
from typing import Dict, List, Any, Optional, Union
import numpy as np


DEFAULT_BASEMAPS = {
    "dark": "https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json",
    "positron": "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json",
    "voyager": "https://basemaps.cartocdn.com/gl/voyager-gl-style/style.json",
    "satellite": "https://api.maptiler.com/maps/hybrid/style.json?key=get_your_own_OpIi9ZULNHzrESv6T2vL"
}


def bbox_to_center_zoom(bbox: List[float]) -> Dict[str, Any]:
    """Calculate center longitude, latitude, and approximate zoom from [min_lon, min_lat, max_lon, max_lat]."""
    min_lon, min_lat, max_lon, max_lat = bbox
    center_lon = (min_lon + max_lon) / 2.0
    center_lat = (min_lat + max_lat) / 2.0

    span_lon = max(1e-4, abs(max_lon - min_lon))
    span_lat = max(1e-4, abs(max_lat - min_lat))
    max_span = max(span_lon, span_lat)

    # Approximate zoom calculation
    zoom = max(1.0, min(18.0, round(np.log2(360.0 / max_span) - 0.5, 1)))
    return {
        "center": [center_lon, center_lat],
        "zoom": float(zoom),
        "bbox": bbox
    }


def export_geolibre_project_json(
    title: str,
    bbox: List[float],
    layers: List[Dict[str, Any]],
    description: str = "Generated by eo-mcp autonomous planetary agent",
    basemap_theme: str = "dark"
) -> Dict[str, Any]:
    """
    Generate a standard GeoLibre project schema JSON object (.geolibre).
    Compatible with GeoLibre Desktop (Tauri) and GeoLibre Web (web.geolibre.app).
    """
    cam = bbox_to_center_zoom(bbox)
    style_url = DEFAULT_BASEMAPS.get(basemap_theme, DEFAULT_BASEMAPS["dark"])

    project = {
        "$schema": "https://geolibre.app/schemas/project-v1.json",
        "name": title,
        "description": description,
        "version": "1.0.0",
        "created_with": "eo-mcp",
        "map": {
            "center": cam["center"],
            "zoom": cam["zoom"],
            "pitch": 25.0,
            "bearing": 0.0,
            "bounds": bbox,
            "style": style_url
        },
        "layers": layers,
        "metadata": {
            "author": "eo-mcp Agentic Planetary Protocol",
            "planetary_data_sources": [
                "Copernicus Sentinel-1/2/5P",
                "NASA/USGS Landsat",
                "Copernicus DEM GLO-30",
                "NASA JPL OPERA"
            ]
        }
    }
    return project


def plan_geoagent_actions(
    bbox: List[float],
    layers: List[Dict[str, Any]],
    narrative: str = "Displaying hazard analytics"
) -> List[Dict[str, Any]]:
    """
    Generate a structured sequence of tool actions compatible with maplibre-gl-geoagent.
    Enables autonomous agents to command an active MapLibre / GeoLibre UI.
    """
    cam = bbox_to_center_zoom(bbox)
    actions = [
        {
            "tool": "flyTo",
            "parameters": {
                "center": cam["center"],
                "zoom": cam["zoom"],
                "pitch": 30.0,
                "bearing": 0.0,
                "speed": 1.2
            },
            "reasoning": f"Orient map canvas to analysis area: {cam['center']} (bbox: {bbox})"
        }
    ]

    for idx, layer in enumerate(layers):
        actions.append({
            "tool": "addLayer",
            "parameters": {
                "id": layer.get("id", f"eo_layer_{idx}"),
                "type": layer.get("type", "fill"),
                "source": layer.get("source"),
                "paint": layer.get("paint", {}),
                "layout": layer.get("layout", {"visibility": "visible"})
            },
            "reasoning": f"Add geospatial layer '{layer.get('id', idx)}' representing {layer.get('name', 'EO dataset')}."
        })

    return actions


def generate_interactive_maplibre_html(
    title: str,
    bbox: List[float],
    geojson_data: Optional[Dict[str, Any]] = None,
    raster_tile_url: Optional[str] = None,
    summary_metrics: Optional[Dict[str, Any]] = None,
    hazard_type: Optional[str] = None
) -> str:
    """
    Generate a complete, self-contained interactive MapLibre GL JS HTML application.
    Features:
    - Apple dark titanium glassmorphic UI overlay
    - Interactive pan, zoom, pitch, and rotation
    - GeoJSON vector overlays with attribute inspection popups
    - Raster tile streaming support (XYZ / COG TiTiler endpoint)
    - Responsive metric scorecard sidebar
    """
    cam = bbox_to_center_zoom(bbox)
    center_lon, center_lat = cam["center"]
    zoom = cam["zoom"]

    geojson_str = json.dumps(geojson_data or {"type": "FeatureCollection", "features": []})
    metrics_html = ""
    if summary_metrics:
        rows = []
        for k, v in summary_metrics.items():
            label = k.replace("_", " ").title()
            rows.append(f"""
                <div class="metric-row">
                    <span class="metric-label">{label}</span>
                    <span class="metric-value">{v}</span>
                </div>
            """)
        metrics_html = "".join(rows)

    hazard_tag = f'<span class="badge">{hazard_type.upper()}</span>' if hazard_type else ""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} — eo-mcp / GeoLibre Viewer</title>
    <!-- MapLibre GL JS -->
    <link href="https://unpkg.com/maplibre-gl@4.7.1/dist/maplibre-gl.css" rel="stylesheet" />
    <script src="https://unpkg.com/maplibre-gl@4.7.1/dist/maplibre-gl.js"></script>
    <style>
        :root {{
            --bg-glass: rgba(15, 23, 42, 0.85);
            --border-glass: rgba(255, 255, 255, 0.12);
            --accent: #38bdf8;
            --accent-gradient: linear-gradient(135deg, #38bdf8 0%, #818cf8 100%);
            --text-main: #f8fafc;
            --text-muted: #94a3b8;
        }}
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body, html {{ width: 100%; height: 100%; overflow: hidden; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif; background: #0b0f19; color: var(--text-main); }}
        #map {{ width: 100%; height: 100%; }}
        
        /* Glassmorphic Panel */
        .glass-panel {{
            position: absolute;
            top: 20px;
            left: 20px;
            width: 360px;
            max-height: calc(100vh - 40px);
            background: var(--bg-glass);
            backdrop-filter: blur(16px);
            -webkit-backdrop-filter: blur(16px);
            border: 1px solid var(--border-glass);
            border-radius: 14px;
            padding: 20px;
            box-shadow: 0 20px 40px rgba(0, 0, 0, 0.5);
            z-index: 10;
            overflow-y: auto;
        }}
        .header {{ display: flex; align-items: center; justify-content: space-between; margin-bottom: 12px; }}
        h1 {{ font-size: 1.15rem; font-weight: 700; color: #fff; letter-spacing: -0.02em; }}
        .badge {{
            background: var(--accent-gradient);
            color: #0b0f19;
            font-size: 0.7rem;
            font-weight: 800;
            padding: 3px 8px;
            border-radius: 9999px;
            letter-spacing: 0.05em;
        }}
        .subtitle {{ font-size: 0.82rem; color: var(--text-muted); margin-bottom: 16px; line-height: 1.4; }}
        
        .metrics-card {{
            background: rgba(255, 255, 255, 0.03);
            border: 1px solid rgba(255, 255, 255, 0.06);
            border-radius: 10px;
            padding: 12px;
            margin-bottom: 16px;
        }}
        .metric-row {{
            display: flex;
            justify-content: space-between;
            padding: 6px 0;
            border-bottom: 1px solid rgba(255, 255, 255, 0.04);
            font-size: 0.85rem;
        }}
        .metric-row:last-child {{ border-bottom: none; }}
        .metric-label {{ color: var(--text-muted); }}
        .metric-value {{ font-weight: 600; color: #e2e8f0; }}

        .controls {{ display: flex; flex-direction: column; gap: 8px; margin-top: 10px; }}
        .btn {{
            background: rgba(255, 255, 255, 0.08);
            border: 1px solid var(--border-glass);
            color: #fff;
            padding: 8px 12px;
            border-radius: 8px;
            font-size: 0.8rem;
            cursor: pointer;
            font-weight: 600;
            transition: all 0.2s ease;
        }}
        .btn:hover {{
            background: rgba(56, 189, 248, 0.2);
            border-color: #38bdf8;
            color: #38bdf8;
        }}
        .footer {{ margin-top: 16px; font-size: 0.72rem; color: #64748b; text-align: center; }}
        
        /* MapLibre Popup Styling */
        .maplibregl-popup-content {{
            background: rgba(15, 23, 42, 0.95) !important;
            backdrop-filter: blur(12px) !important;
            color: #f8fafc !important;
            border: 1px solid var(--border-glass) !important;
            border-radius: 10px !important;
            padding: 12px 16px !important;
            box-shadow: 0 10px 25px rgba(0,0,0,0.6) !important;
            font-size: 0.85rem !important;
        }}
        .maplibregl-popup-tip {{ border-top-color: rgba(15, 23, 42, 0.95) !important; }}
    </style>
</head>
<body>
    <div class="glass-panel">
        <div class="header">
            <h1>{title}</h1>
            {hazard_tag}
        </div>
        <p class="subtitle">Generated autonomously by <strong>eo-mcp</strong> with MapLibre GL engine. Fully compatible with GeoLibre open GIS.</p>
        
        <div class="metrics-card">
            {metrics_html}
        </div>

        <div class="controls">
            <button class="btn" onclick="resetView()">Reset Bounding View</button>
            <button class="btn" onclick="togglePitch()">Toggle 3D Perspective</button>
        </div>

        <div class="footer">
            eo-mcp Planetary Model Context Protocol &bull; GeoLibre Compatible
        </div>
    </div>

    <div id="map"></div>

    <script>
        const initialCenter = [{center_lon}, {center_lat}];
        const initialZoom = {zoom};
        const initialBbox = {json.dumps(bbox)};
        const geojsonData = {geojson_str};

        const map = new maplibregl.Map({{
            container: 'map',
            style: 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json',
            center: initialCenter,
            zoom: initialZoom,
            pitch: 20
        }});

        map.addControl(new maplibregl.NavigationControl({{ visualizePitch: true }}), 'top-right');
        map.addControl(new maplibregl.ScaleControl({{ unit: 'metric' }}), 'bottom-right');

        map.on('load', () => {{
            // Add GeoJSON data source
            if (geojsonData.features && geojsonData.features.length > 0) {{
                map.addSource('hazard-features', {{
                    type: 'geojson',
                    data: geojsonData
                }});

                // Polygons
                map.addLayer({{
                    id: 'hazard-polygons-fill',
                    type: 'fill',
                    source: 'hazard-features',
                    filter: ['==', '$type', 'Polygon'],
                    paint: {{
                        'fill-color': [
                            'case',
                            ['has', 'fill'], ['get', 'fill'],
                            ['has', 'color'], ['get', 'color'],
                            '#ef4444'
                        ],
                        'fill-opacity': 0.6
                    }}
                }});

                map.addLayer({{
                    id: 'hazard-polygons-line',
                    type: 'line',
                    source: 'hazard-features',
                    filter: ['==', '$type', 'Polygon'],
                    paint: {{
                        'line-color': '#ffffff',
                        'line-width': 1.5,
                        'line-opacity': 0.8
                    }}
                }});

                // LineStrings
                map.addLayer({{
                    id: 'hazard-lines',
                    type: 'line',
                    source: 'hazard-features',
                    filter: ['==', '$type', 'LineString'],
                    paint: {{
                        'line-color': [
                            'case',
                            ['has', 'stroke'], ['get', 'stroke'],
                            '#38bdf8'
                        ],
                        'line-width': 3
                    }}
                }});

                // Points / Hotspots / Vessels
                map.addLayer({{
                    id: 'hazard-points',
                    type: 'circle',
                    source: 'hazard-features',
                    filter: ['==', '$type', 'Point'],
                    paint: {{
                        'circle-radius': 6,
                        'circle-color': [
                            'case',
                            ['has', 'marker-color'], ['get', 'marker-color'],
                            '#f59e0b'
                        ],
                        'circle-stroke-width': 1.5,
                        'circle-stroke-color': '#ffffff'
                    }}
                }});

                // Popup on Click
                const layers = ['hazard-polygons-fill', 'hazard-lines', 'hazard-points'];
                layers.forEach(lyr => {{
                    map.on('click', lyr, (e) => {{
                        const f = e.features[0];
                        const props = f.properties || {{}};
                        let content = '<div><strong style="color:#38bdf8">Feature Attributes</strong></div>';
                        for (const [k, v] of Object.entries(props)) {{
                            content += `<div><span style="color:#94a3b8">${{k}}:</span> <strong>${{v}}</strong></div>`;
                        }}
                        new maplibregl.Popup()
                            .setLngLat(e.lngLat)
                            .setHTML(content)
                            .addTo(map);
                    }});

                    map.on('mouseenter', lyr, () => map.getCanvas().style.cursor = 'pointer');
                    map.on('mouseleave', lyr, () => map.getCanvas().style.cursor = '');
                }});
            }}

            // Fit initial bbox
            if (initialBbox && initialBbox.length === 4) {{
                map.fitBounds([
                    [initialBbox[0], initialBbox[1]],
                    [initialBbox[2], initialBbox[3]]
                ], {{ padding: 60, maxZoom: 15 }});
            }}
        }});

        function resetView() {{
            map.fitBounds([
                [initialBbox[0], initialBbox[1]],
                [initialBbox[2], initialBbox[3]]
            ], {{ padding: 60, duration: 1500 }});
        }}

        let is3D = false;
        function togglePitch() {{
            is3D = !is3D;
            map.easeTo({{
                pitch: is3D ? 60 : 0,
                bearing: is3D ? 30 : 0,
                duration: 1000
            }});
        }}
    </script>
</body>
</html>
"""
    return html


def generate_bitemporal_swipe_map_html(
    title: str,
    bbox: List[float],
    epoch1_label: str = "Epoch 1 (Baseline)",
    epoch2_label: str = "Epoch 2 (Comparison)",
    geojson_overlay: Optional[Dict[str, Any]] = None,
    summary_caption: Optional[str] = None
) -> str:
    """
    Generate an interactive MapLibre GL JS Bitemporal Swipe / Comparison Map.

    Provides a synchronized dual-layer view with opacity/swipe slider for comparing
    multi-temporal satellite acquisitions with vectorized change anomaly overlays.

    Args:
        title: Project title.
        bbox: [min_lon, min_lat, max_lon, max_lat] in EPSG:4326.
        epoch1_label: Label for baseline observation.
        epoch2_label: Label for comparison observation.
        geojson_overlay: Optional GeoJSON FeatureCollection of change polygons.
        summary_caption: Optional natural language change summary.

    Returns:
        Self-contained HTML5 page string.
    """
    center_info = bbox_to_center_zoom(bbox)
    geojson_str = json.dumps(geojson_overlay) if geojson_overlay else "null"
    caption_escaped = (summary_caption or "").replace('"', '&quot;').replace("'", "&#39;")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{title} - Bitemporal Change Map</title>
    <link href="https://unpkg.com/maplibre-gl@3.6.2/dist/maplibre-gl.css" rel="stylesheet" />
    <script src="https://unpkg.com/maplibre-gl@3.6.2/dist/maplibre-gl.js"></script>
    <style>
        body, html {{ margin: 0; padding: 0; width: 100%; height: 100%; background: #0b0f17; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #f1f5f9; overflow: hidden; }}
        #map {{ width: 100%; height: 100%; }}
        .header-bar {{ position: absolute; top: 16px; left: 16px; z-index: 10; background: rgba(15, 23, 42, 0.90); backdrop-filter: blur(12px); border: 1px solid rgba(56, 189, 248, 0.25); border-radius: 8px; padding: 14px 20px; max-width: 480px; box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.5); }}
        .title {{ font-size: 16px; font-weight: 700; color: #38bdf8; margin: 0 0 6px 0; }}
        .caption {{ font-size: 12px; color: #cbd5e1; line-height: 1.5; margin: 0; }}
        .controls-card {{ position: absolute; bottom: 24px; left: 16px; z-index: 10; background: rgba(15, 23, 42, 0.90); backdrop-filter: blur(12px); border: 1px solid rgba(56, 189, 248, 0.25); border-radius: 8px; padding: 12px 18px; }}
        .slider-label {{ font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: #94a3b8; margin-bottom: 6px; }}
        .slider-row {{ display: flex; align-items: center; gap: 12px; }}
        input[type="range"] {{ width: 220px; accent-color: #38bdf8; cursor: pointer; }}
        .badge {{ font-size: 11px; font-weight: 600; padding: 2px 6px; border-radius: 4px; background: rgba(56, 189, 248, 0.15); color: #38bdf8; }}
    </style>
</head>
<body>
    <div class="header-bar">
        <h1 class="title">{title}</h1>
        <p class="caption">{caption_escaped}</p>
    </div>

    <div class="controls-card">
        <div class="slider-label">Temporal Blend Ratio</div>
        <div class="slider-row">
            <span class="badge">{epoch1_label}</span>
            <input type="range" id="blend-slider" min="0" max="100" value="50" oninput="updateBlend(this.value)" />
            <span class="badge">{epoch2_label}</span>
        </div>
    </div>

    <div id="map"></div>

    <script>
        const initialBbox = {json.dumps(bbox)};
        const changeGeojson = {geojson_str};

        const map = new maplibregl.Map({{
            container: 'map',
            style: 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json',
            center: [{center_info['center'][0]}, {center_info['center'][1]}],
            zoom: {center_info['zoom']}
        }});

        map.addControl(new maplibregl.NavigationControl(), 'top-right');

        map.on('load', () => {{
            if (changeGeojson && changeGeojson.features && changeGeojson.features.length > 0) {{
                map.addSource('change-polygons', {{
                    type: 'geojson',
                    data: changeGeojson
                }});

                map.addLayer({{
                    id: 'change-fill',
                    type: 'fill',
                    source: 'change-polygons',
                    paint: {{
                        'fill-color': '#ef4444',
                        'fill-opacity': 0.45
                    }}
                }});

                map.addLayer({{
                    id: 'change-line',
                    type: 'line',
                    source: 'change-polygons',
                    paint: {{
                        'line-color': '#f87171',
                        'line-width': 2
                    }}
                }});

                map.on('click', 'change-fill', (e) => {{
                    const props = e.features[0].properties || {{}};
                    let content = '<div style="color:#ef4444;font-weight:700">Change Anomaly Patch</div>';
                    for (const [k, v] of Object.entries(props)) {{
                        content += `<div><span style="color:#94a3b8">${{k}}:</span> <strong>${{v}}</strong></div>`;
                    }}
                    new maplibregl.Popup()
                        .setLngLat(e.lngLat)
                        .setHTML(content)
                        .addTo(map);
                }});

                map.on('mouseenter', 'change-fill', () => map.getCanvas().style.cursor = 'pointer');
                map.on('mouseleave', 'change-fill', () => map.getCanvas().style.cursor = '');
            }}

            if (initialBbox && initialBbox.length === 4) {{
                map.fitBounds([
                    [initialBbox[0], initialBbox[1]],
                    [initialBbox[2], initialBbox[3]]
                ], {{ padding: 60, maxZoom: 15 }});
            }}
        }});

        function updateBlend(val) {{
            const opacity = val / 100.0;
            if (map.getLayer('change-fill')) {{
                map.setPaintProperty('change-fill', 'fill-opacity', opacity * 0.7);
            }}
        }}
    </script>
</body>
</html>
"""
    return html

